### ISSUE TITLE
Still show unused warning on export default function component

### ISSUE THREAD

**Issue by yangbo5207** [vue-vine/vue-vine#129] opened 2024-07-24 03:26 UTC
<img width="554" alt="image" src="https://github.com/user-attachments/assets/bbcad0bd-e179-46cd-9e9f-0620f91c131d">

如图所示，`exprot default App` ，但仍然提示声明的函数未使用

**Comment by ShenQingchuan** [comment] 2024-07-26 17:56
@yangbo5207 

Hello，我在本地没有复现，请提供以下你现在 项目的 `package.json` 文件和 VSCode 当前 Vue Vine 插件的版本号

————————————————————
Hello, I couldn't reproduce it locally. Could you please provide the following information about your current project: the contents of your `package.json` file and the version number of the currently installed Vue Vine extension in VSCode?

**Comment by ShenQingchuan** [comment] 2024-08-26 14:29
Seems resolved with your reproduction repo in the latest version VSCode extension
https://github.com/yangbo5207/vuevinedemo

**Closed by ShenQingchuan** 2024-08-26 14:29 UTC
Labels: bug, vscode-ext, need reproduction
