### ISSUE TITLE
Using UnoCSS in template not working

### ISSUE THREAD

**Issue by kalu5** [vue-vine/vue-vine#162] opened 2024-11-13 03:49 UTC
示例代码：
``` 
export default function Order() {
  return vine`<div class="h-40 bg-red text-red text-sm">
    <div class="font-600 text-lg" >hello</div>
  </div>
  `;
}
```
结果：
![Image_20241113114842](https://github.com/user-attachments/assets/088ac465-ec4e-47e2-a117-9652efe445ea)

**Comment by yuxi-ovo** [comment] 2024-11-14 16:05
有没有更多的信息 比如你的main.ts是如何导入UnoCss的 报错的具体代码是什么

**Comment by ShenQingchuan** [comment] 2024-11-15 14:34
Maybe duplicated as https://github.com/vue-vine/vue-vine/issues/148 ??

Please check if you configured UnoCSS correctly.

Please provide more information or a minimal reproduction so that we're able to help you.

**Comment by kalu5** [comment] 2024-11-16 03:44
I simply built a project and the style is normal.  I'm taking a look.

**Comment by ShenQingchuan** [comment] 2024-11-16 13:49
Would you like to share that project's repo link and we can check it out to find the problem.

**Comment by ShenQingchuan** [comment] 2024-11-22 07:38
Since this discussion is no longer active, I'm temporarily close this issue.
Feel free to re-open it if you need.

**Closed by ShenQingchuan** 2024-11-22 07:38 UTC
Labels: need-more-information, need reproduction
